### ISSUE TITLE
Display problems

### ISSUE THREAD

**Issue by RicardoJ** [the-darkvoid/XPS9530-OSX#13]
My XPS 9530 with a 15.6-inch UltraSharp 4K Ultra HD (3840 x 2160) touch display is not working correctly. The screen flickers a lot. I think these patches for the XPS 9530 are going till 3x1200 and not above. Is there a fix so I can use the native resolution or 1920x1080.

**Comment by syscl** [comment]
Try https://github.com/syscl/M3800 which has added support for 4K model for both M3800 and XPS9530.

**Comment by RicardoJ** [comment]
Something I got to apply manually or to re-install the whole system?

**Comment by syscl** [comment]
1. Re-install the whole system is no needed.
2. Re-dump ACPI tables by pressing (Fn+)F4. 
3. Replace the Clover folder with the one under https://github.com/syscl/M3800/tree/M3800/CLOVER
4. Remove previous patched ACPI tables under /Volumes/EFI/EFI/Clover/ACPI/patched/
5. Remove /Library/Extensions/AppleHDA_ALC668.kext and /Library/Extensions/CodecCommnader.kext
7. Run the deploy.sh by typing following under terminate:
``` sh 
git clone https://github.com/syscl/M3800
chmod +x ./M3800/deploy.sh
cd M3800
./deploy.sh
```

For more details see [here] (https://github.com/syscl/M3800)
P.S. Since you have successfully installed OS X on your XPS9530, the procedure is really easy, just execute the deploy.sh will finish almost all the operations for you. Good luck!

syscl

**Comment by RicardoJ** [comment]
That didn't work as suddenly I have a Iris pro as device and there are really messed up lines in the screen and the transparency in Mac is making it not nice. Is there a fix for that?

**Comment by syscl** [comment]
Yes, I used to suffer from that issue too, the fix is typing:
``` sh
sudo touch /System/Library/Extensions && sudo touch /Library/Extensions && sudo kextcache -u /
```
Then boot without caches under Clove. [Note: the bios setting in my BIOS is 
- Chipset:
    PCH-IO Configuration/XHCI Mode = Smart Auto

    System Agent (SA) Configuration/Graphics Configuration:
        Aperture Size = 512MB
        DVMT Pre-Allocated = 160MB
        DVMT Total Gfx Mem = MAX
]

**Comment by RicardoJ** [comment]
Thank you for this solution. However, it seems with your suggestions, the screen still goes wild. Do you got any other solution or is it back to Linux for me? It seems that nobody with this model seems to have the genuine resolutions. I tried SwitchX and various other display tools.

**Comment by syscl** [comment]
Ummm, strange, but they report they've succeed with 4K model. See https://github.com/syscl/M3800/issues/6

1. You can try my Clover with its config.plist and then re-run deploy.sh again.

Best wishes!

**Comment by RicardoJ** [comment]
Unsolved.
